#!/usr/bin/env node

/**
 * build-avatar.js
 *
 * Refreshes the avatar baked into the package. Run manually:
 *   node build-avatar.js
 *
 * Workflow:
 *   1. Downloads your github avatar
 *   2. Resizes + grayscales
 *   3. Maps each pixel's brightness onto an amber gradient (phosphor look)
 *   4. Encodes as ANSI half-block art (▀)
 *   5. Writes to ./avatar.js as a default-exported string
 *
 * Requires sharp:
 *   npm install --save-dev sharp
 */

import sharp from "sharp";
import https from "node:https";
import fs from "node:fs/promises";
import { USERNAME, AVATAR_WIDTH, AVATAR_HEIGHT } from "./config.js";

// ─────────────────────────────────────────────────────────────
// amber palette — dark to bright
// these are the same hex values used in the card's chalk palette
// ─────────────────────────────────────────────────────────────
const AMBER_STOPS = [
  [10, 5, 0],       // near-black (deep shadow)
  [69, 26, 3],      // very faint amber
  [120, 53, 15],    // burned-in
  [146, 64, 14],    // dim amber
  [180, 83, 9],
  [217, 119, 6],
  [251, 191, 36],   // bright amber (highlight)
  [252, 211, 77],   // pale amber (specular)
];

// linear interpolation between two RGB colors
function lerpColor(a, b, t) {
  return [
    Math.round(a[0] + (b[0] - a[0]) * t),
    Math.round(a[1] + (b[1] - a[1]) * t),
    Math.round(a[2] + (b[2] - a[2]) * t),
  ];
}

// map a brightness value (0-255) onto the amber gradient
function amberize(brightness) {
  const t = brightness / 255;
  const scaled = t * (AMBER_STOPS.length - 1);
  const idx = Math.floor(scaled);
  const frac = scaled - idx;
  if (idx >= AMBER_STOPS.length - 1) return AMBER_STOPS[AMBER_STOPS.length - 1];
  return lerpColor(AMBER_STOPS[idx], AMBER_STOPS[idx + 1], frac);
}

// ─────────────────────────────────────────────────────────────
// download
// ─────────────────────────────────────────────────────────────
function download(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": "npx-card-build" } }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          return download(res.headers.location).then(resolve, reject);
        }
        if (res.statusCode !== 200) {
          return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
        }
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => resolve(Buffer.concat(chunks)));
        res.on("error", reject);
      })
      .on("error", reject);
  });
}

// ─────────────────────────────────────────────────────────────
// half-block encoder with amber tinting
// ─────────────────────────────────────────────────────────────
async function imageToAnsi(imageBuffer) {
  const pixelWidth = AVATAR_WIDTH;
  const pixelHeight = AVATAR_HEIGHT * 2;

  // grayscale + slight contrast boost so the amber gradient hits its range
  const { data, info } = await sharp(imageBuffer)
    .resize(pixelWidth, pixelHeight, { fit: "cover", position: "centre" })
    .grayscale()
    .linear(1.15, -15) // gentle contrast — preserves face detail
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const W = info.width;
  const H = info.height;
  const channels = info.channels;

  const brightness = (x, y) => {
    const i = (y * W + x) * channels;
    // after grayscale, R=G=B; just take R
    return data[i];
  };

  const lines = [];
  for (let y = 0; y < H; y += 2) {
    let line = "";
    for (let x = 0; x < W; x++) {
      const top = amberize(brightness(x, y));
      const bot = amberize(y + 1 < H ? brightness(x, y + 1) : brightness(x, y));
      line += `\x1b[38;2;${top[0]};${top[1]};${top[2]};48;2;${bot[0]};${bot[1]};${bot[2]}m\u2580`;
    }
    line += "\x1b[0m";
    lines.push(line);
  }
  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────
// main
// ─────────────────────────────────────────────────────────────
async function main() {
  const avatarUrl = `https://avatars.githubusercontent.com/${USERNAME}?s=460&v=4`;
  console.log(`→ Downloading avatar for @${USERNAME}...`);
  const buf = await download(avatarUrl);
  console.log(`  got ${buf.length} bytes`);

  console.log(`→ Rendering to ${AVATAR_WIDTH}×${AVATAR_HEIGHT} amber-tinted half-blocks...`);
  const ansi = await imageToAnsi(buf);

  const out = `// auto-generated by build-avatar.js — do not edit
export default ${JSON.stringify(ansi)};
`;

  await fs.writeFile("./avatar.js", out, "utf8");
  console.log(`→ Wrote avatar.js (${out.length} bytes)`);
  console.log(`\nDone. Now commit avatar.js and publish.`);
}

main().catch((err) => {
  console.error("BUILD FAILED:", err.message);
  process.exit(1);
});
