#!/usr/bin/env node

/**
 * build-avatar.js
 *
 * Refreshes the avatar baked into the package. Run manually:
 *   node build-avatar.js
 *
 * Workflow:
 *   1. Downloads your github avatar (live, full resolution)
 *   2. Resizes to AVATAR_WIDTH × (AVATAR_HEIGHT × 2) pixels
 *   3. Encodes as ANSI half-block art (▀) with foreground+background per cell
 *   4. Writes to ./avatar.js as a default-exported string
 *
 * Then commit avatar.js, bump version, and `npm publish`.
 *
 * Requires sharp as a devDependency:
 *   npm install --save-dev sharp
 */

import sharp from "sharp";
import https from "node:https";
import fs from "node:fs/promises";
import { USERNAME, AVATAR_WIDTH, AVATAR_HEIGHT } from "./config.js";

// ─────────────────────────────────────────────────────────────
// download with redirect following
// ─────────────────────────────────────────────────────────────
function download(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": "npx-card-build" } }, (res) => {
        if (
          res.statusCode >= 300 &&
          res.statusCode < 400 &&
          res.headers.location
        ) {
          return download(res.headers.location).then(resolve, reject);
        }
        if (res.statusCode !== 200) {
          return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
        }
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => resolve(Buffer.concat(chunks)));
        res.on("error", reject);
      })
      .on("error", reject);
  });
}

// ─────────────────────────────────────────────────────────────
// half-block encoder
// ─────────────────────────────────────────────────────────────
// each character row = 2 vertical pixels
// "▀" = upper half block; foreground = top pixel, background = bottom pixel
async function imageToAnsi(imageBuffer) {
  const pixelWidth = AVATAR_WIDTH;
  const pixelHeight = AVATAR_HEIGHT * 2;

  const { data, info } = await sharp(imageBuffer)
    .resize(pixelWidth, pixelHeight, { fit: "cover", position: "centre" })
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  // safety: sharp may pad output by a row; trust info.width / info.height
  const W = info.width;
  const H = info.height;
  const channels = info.channels; // should be 3 after removeAlpha

  const pixel = (x, y) => {
    const i = (y * W + x) * channels;
    return [data[i], data[i + 1], data[i + 2]];
  };

  const lines = [];
  for (let y = 0; y < H; y += 2) {
    let line = "";
    for (let x = 0; x < W; x++) {
      const [r1, g1, b1] = pixel(x, y);
      const [r2, g2, b2] = y + 1 < H ? pixel(x, y + 1) : [r1, g1, b1];
      // foreground = top pixel; background = bottom pixel; glyph = ▀
      line +=
        `\x1b[38;2;${r1};${g1};${b1};48;2;${r2};${g2};${b2}m\u2580`;
    }
    line += "\x1b[0m"; // reset at end of each line so background doesn't bleed
    lines.push(line);
  }
  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────
// main
// ─────────────────────────────────────────────────────────────
async function main() {
  const avatarUrl = `https://avatars.githubusercontent.com/${USERNAME}?s=460&v=4`;
  console.log(`→ Downloading avatar for @${USERNAME}...`);
  const buf = await download(avatarUrl);
  console.log(`  got ${buf.length} bytes`);

  console.log(`→ Rendering to ${AVATAR_WIDTH}×${AVATAR_HEIGHT} half-blocks...`);
  const ansi = await imageToAnsi(buf);

  // emit as a JS module
  // JSON.stringify handles all the escape characters (including \x1b → \u001b)
  const out = `// auto-generated by build-avatar.js — do not edit
export default ${JSON.stringify(ansi)};
`;

  await fs.writeFile("./avatar.js", out, "utf8");
  console.log(`→ Wrote avatar.js (${out.length} bytes)`);
  console.log(`\nDone. Now commit avatar.js and publish.`);
}

main().catch((err) => {
  console.error("BUILD FAILED:", err.message);
  process.exit(1);
});
